// Package perms centralizes file and directory permission constants for all
// artifacts generated by config-builder.
//
// Design principle:
//   - Private keys and files that embed secrets are owner-only (0600). TLS
//     servers such as PostgreSQL refuse to start if their key material is
//     group- or world-readable.
//   - Everything else is world-readable (0644) and every generated directory
//     is world-traversable (0755). This lets the generated tree be copied to
//     another host and consumed by container processes whose UID/GID do not
//     match the host user that ran config-builder.
package perms

import "os"

const (
	// FilePrivateKey is for TLS/MSP private key material (server.key, node.key,
	// priv_sk). Must be 0600 or PostgreSQL / most TLS stacks will refuse to load it.
	FilePrivateKey os.FileMode = 0o600

	// FileSecret is for configuration files that embed secrets (PINs, passwords).
	FileSecret os.FileMode = 0o600

	// FileCert is for X.509 certificates and other public cryptographic material.
	FileCert os.FileMode = 0o644

	// FileConfig is for generated configuration files (YAML/YML).
	FileConfig os.FileMode = 0o644

	// FilePublic is for non-sensitive artifacts such as genesis.block and
	// docker-compose.yaml.
	FilePublic os.FileMode = 0o644

	// Dir is the permission for every directory created by config-builder.
	Dir os.FileMode = 0o755
)
