package crypto

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"config-builder/internal/config"
)

func TestFabricCANormalizeEnrolledMSPMatchesCryptogenLayout(t *testing.T) {
	mspDir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(mspDir, "signcerts"), 0755); err != nil {
		t.Fatalf("create signcerts: %v", err)
	}
	if err := os.MkdirAll(filepath.Join(mspDir, "cacerts"), 0755); err != nil {
		t.Fatalf("create cacerts: %v", err)
	}
	if err := os.WriteFile(filepath.Join(mspDir, "signcerts", "cert.pem"), []byte("cert"), 0644); err != nil {
		t.Fatalf("write cert: %v", err)
	}
	if err := os.WriteFile(filepath.Join(mspDir, "cacerts", "ca-host-7054.pem"), []byte("ca"), 0644); err != nil {
		t.Fatalf("write ca: %v", err)
	}

	g := NewFabricCAGenerator(&config.NetworkConfig{}, t.TempDir(), "quiet", false)
	if err := g.normalizeEnrolledMSP(mspDir, "org1.example.com", "Admin@org1.example.com"); err != nil {
		t.Fatalf("normalizeEnrolledMSP: %v", err)
	}

	for _, want := range []string{
		filepath.Join(mspDir, "signcerts", "Admin@org1.example.com-cert.pem"),
		filepath.Join(mspDir, "cacerts", "ca.org1.example.com-cert.pem"),
	} {
		if _, err := os.Stat(want); err != nil {
			t.Fatalf("expected normalized file %s: %v", want, err)
		}
	}
}

func TestFabricCAGenerateOrgCryptoRejectsEmptyNodeSet(t *testing.T) {
	g := NewFabricCAGenerator(&config.NetworkConfig{}, t.TempDir(), "quiet", false)
	if err := g.GenerateOrgCrypto("Org1", "org1.example.com", "http://ca.example.com:7054", "token", nil, "peer"); err == nil {
		t.Fatal("expected empty node set to fail")
	}
}

func TestFabricCACopyFileCreatesDestinationDirectory(t *testing.T) {
	srcDir := t.TempDir()
	src := filepath.Join(srcDir, "source.pem")
	if err := os.WriteFile(src, []byte("cert"), 0644); err != nil {
		t.Fatalf("write source: %v", err)
	}

	dst := filepath.Join(t.TempDir(), "nested", "dir", "dest.pem")
	g := NewFabricCAGenerator(&config.NetworkConfig{}, t.TempDir(), "quiet", false)
	if err := g.copyFile(src, dst); err != nil {
		t.Fatalf("copyFile: %v", err)
	}

	got, err := os.ReadFile(dst)
	if err != nil {
		t.Fatalf("read destination: %v", err)
	}
	if string(got) != "cert" {
		t.Fatalf("unexpected destination contents: %q", string(got))
	}
}

func TestNonAdminUsersFiltersAutoGeneratedAdmin(t *testing.T) {
	users := nonAdminUsers([]config.User{
		{Name: "Admin"},
		{Name: "User1"},
		{Name: "channel_admin"},
	})

	if len(users) != 2 {
		t.Fatalf("expected two non-admin users, got %#v", users)
	}
	for _, user := range users {
		if user.Name == "Admin" {
			t.Fatalf("Admin should be filtered because Fabric CA generates it separately: %#v", users)
		}
	}
}

func TestWriteFabricCAClientConfigUsesVendoredTemplate(t *testing.T) {
	g := NewFabricCAGenerator(&config.NetworkConfig{}, t.TempDir(), "quiet", false)
	configPath := filepath.Join(t.TempDir(), "nested", "fabric-ca-client-config.yaml")

	if err := g.writeFabricCAClientConfig(configPath, "org1-token", "1234"); err != nil {
		t.Fatalf("writeFabricCAClientConfig: %v", err)
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("read rendered config: %v", err)
	}
	rendered := string(data)

	for _, want := range []string{
		"bccsp:",
		"default: PKCS11",
		"Library: ./libkms_pkcs11.so",
		"Label: org1-token",
		"Pin: 1234",
		"Hash: SHA2",
		"Security: 256",
	} {
		if !strings.Contains(rendered, want) {
			t.Fatalf("rendered config missing %q:\n%s", want, rendered)
		}
	}
}

func TestWriteFabricCAClientConfigAllowsLibraryOverride(t *testing.T) {
	t.Setenv("FABRIC_CA_CLIENT_PKCS11_LIBRARY", "/opt/fabric/libkms_pkcs11.so")

	g := NewFabricCAGenerator(&config.NetworkConfig{}, t.TempDir(), "quiet", false)
	configPath := filepath.Join(t.TempDir(), "fabric-ca-client-config.yaml")

	if err := g.writeFabricCAClientConfig(configPath, "token", "pin"); err != nil {
		t.Fatalf("writeFabricCAClientConfig: %v", err)
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("read rendered config: %v", err)
	}
	if !strings.Contains(string(data), "Library: /opt/fabric/libkms_pkcs11.so") {
		t.Fatalf("expected overridden library path, got:\n%s", string(data))
	}
}
