// Package fxconfig generates the fxconfig client configuration file that
// accompanies the generated network. The file ships mTLS material and service
// addresses so that callers (e.g. `make create-ns`) can invoke fxconfig with
// `--config /workspace/out/fxconfig.yaml` instead of injecting a dozen env vars.
package fxconfig

import (
	"fmt"
	"os"
	"path/filepath"

	"config-builder/internal/config"
	"config-builder/internal/perms"
)

const fxconfigFileName = "fxconfig.yaml"

// Generate writes fxconfig.yaml at the root of outputDir. Paths embedded in
// the file are container-internal (/workspace/...) because fxconfig is meant
// to run inside the cbdc-tool image with the project directory bind-mounted at
// /workspace. Service addresses default to localhost; deployments against a
// remote network override them via FXCONFIG_*_ADDRESS env vars.
func Generate(cfg *config.NetworkConfig, outputDir string) error {
	if len(cfg.PeerOrgs) == 0 {
		return fmt.Errorf("fxconfig: network has no peer organizations")
	}

	absOut, err := filepath.Abs(outputDir)
	if err != nil {
		return fmt.Errorf("fxconfig: resolve output dir: %w", err)
	}

	peerOrg := cfg.PeerOrgs[0]
	domain := peerOrg.Domain
	mspID := config.DeriveMSPID(peerOrg.Name)

	cryptoBase := filepath.Join(absOut, "build", "config", "cryptogen-artifacts",
		"crypto", "peerOrganizations", domain)

	mspDir := filepath.Join(cryptoBase, "users", "channel_admin@"+domain, "msp")

	channel := cfg.ChannelID
	if channel == "" {
		channel = "arma"
	}

	tlsSection := "tls:\n  enabled: false\n"
	if cfg.TLS != nil && cfg.TLS.Enabled {
		// Reuse the committer-sidecar node's TLS key/cert as the fxconfig mTLS
		// client identity — same tlsCA is trusted by every orderer + committer
		// endpoint. channel_admin has only MSP (signing) material, not TLS.
		tlsDir := filepath.Join(cryptoBase, "peers", "committer-sidecar."+domain, "tls")
		tlsRootCA := filepath.Join(mspDir, "tlscacerts", "tlsca."+domain+"-cert.pem")
		tlsSection = fmt.Sprintf(`tls:
  enabled: true
  clientKey: %s
  clientCert: %s
  rootCerts:
    - %s
`,
			filepath.Join(tlsDir, "server.key"),
			filepath.Join(tlsDir, "server.crt"),
			tlsRootCA,
		)
	}

	content := fmt.Sprintf(`# Generated by config-builder. Paths are container-internal (/workspace/...)
# because fxconfig runs inside the cbdc-tool image. Override service addresses
# with FXCONFIG_ORDERER_ADDRESS / FXCONFIG_QUERIES_ADDRESS /
# FXCONFIG_NOTIFICATIONS_ADDRESS (e.g. to point at a remote deployment).
# Override the PKCS#11 token label/PIN with FXCONFIG_MSP_BCCSP_PKCS11_LABEL /
# FXCONFIG_MSP_BCCSP_PKCS11_PIN — those are runtime secrets and are not baked
# into this file.
logging:
  level: error
msp:
  localMspID: %s
  configPath: %s
  bccsp:
    pkcs11:
      library: /app/libkms_pkcs11.so
      hash: SHA2
      security: 256
%sorderer:
  channel: %s
  address: localhost:7050
  connectionTimeout: 60s
queries:
  address: localhost:5500
  connectionTimeout: 60s
notifications:
  address: localhost:5400
  connectionTimeout: 30s
  waitingTimeout: 30s
`,
		mspID,
		mspDir,
		tlsSection,
		channel,
	)

	dst := filepath.Join(outputDir, fxconfigFileName)
	if err := os.WriteFile(dst, []byte(content), perms.FileConfig); err != nil {
		return fmt.Errorf("fxconfig: write %s: %w", dst, err)
	}
	return nil
}
