package genesis

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"config-builder/internal/config"
)

// Generator handles genesis block generation
// Note: configtxgen is always run via Docker container (no local source available)
type Generator struct {
	config    *config.NetworkConfig
	outputDir string
	verbose   bool
}

// NewGenerator creates a new genesis block generator
func NewGenerator(cfg *config.NetworkConfig, outputDir string, verbose bool) *Generator {
	return &Generator{
		config:    cfg,
		outputDir: outputDir,
		verbose:   verbose,
	}
}

// Generate generates the genesis block
func (g *Generator) Generate() error {
	// Step 1: Create placeholder shared_config.binpb if it doesn't exist
	// TODO: This should be generated by armageddon tool in the future
	if err := g.createPlaceholderSharedConfig(); err != nil {
		g.log("Warning: failed to create placeholder shared_config.binpb: %v", err)
	}

	// Step 2: Generate configtx.yaml
	configPath, err := g.generateConfigtx()
	if err != nil {
		return fmt.Errorf("failed to generate configtx.yaml: %w", err)
	}

	// Step 3: Try to find configtxgen (prefer Docker container, fallback to local binary)
	if err := g.findConfigtxgen(); err != nil {
		// If configtxgen is not available, just generate configtx.yaml
		g.log("configtxgen not found, only configtx.yaml was generated")
		g.log("  To generate genesis block, please install configtxgen or build it from source")
		return nil
	}

	// Step 4: Run configtxgen
	if err := g.runConfigtxgen(configPath); err != nil {
		return fmt.Errorf("failed to run configtxgen: %w", err)
	}

	return nil
}

// createPlaceholderSharedConfig is no longer needed as armageddon is integrated
// This function is kept for backward compatibility but does nothing
func (g *Generator) createPlaceholderSharedConfig() error {
	// Armageddon integration is now complete, no placeholder needed
	return nil
}

// GenerateConfigtxOnly generates only the configtx.yaml file
func (g *Generator) GenerateConfigtxOnly() (string, error) {
	return g.generateConfigtx()
}

// findConfigtxgen verifies configtxgen is available (either via Docker or local binary)
func (g *Generator) findConfigtxgen() error {
	// If use_local_tools is enabled, check for local configtxgen binary
	if g.config.Docker.UseLocalTools {
		if _, err := exec.LookPath("configtxgen"); err != nil {
			return fmt.Errorf("configtxgen not found in PATH. Please install it or use Docker mode (set use_local_tools: false)")
		}
		g.log("Using local configtxgen binary")
		return nil
	}

	// Docker mode: check if Docker is available
	if !g.checkDockerConfigtxgen() {
		return fmt.Errorf("Docker is required to run configtxgen. Please ensure Docker is installed and the image %s contains configtxgen", g.config.Docker.ToolsImage)
	}

	g.log("Using configtxgen from Docker container: %s", g.config.Docker.ToolsImage)
	return nil
}

// checkDockerConfigtxgen checks if Docker and the tools image with configtxgen are available
func (g *Generator) checkDockerConfigtxgen() bool {
	// Check if docker command is available
	if _, err := exec.LookPath("docker"); err != nil {
		g.log("Docker not found in PATH")
		return false
	}

	// Get the image name
	image := g.config.Docker.ToolsImage
	if image == "" {
		image = "docker.io/hyperledger/fabric-x-tools:0.0.4" // Default from Ansible
	}

	// Try to inspect the image to see if it exists
	cmd := exec.Command("docker", "image", "inspect", image)
	cmd.Stdout = nil
	cmd.Stderr = nil
	if err := cmd.Run(); err == nil {
		// Image exists, check if it contains configtxgen
		testCmd := exec.Command("docker", "run", "--rm", image, "sh", "-c", "command -v configtxgen")
		testCmd.Stdout = nil
		testCmd.Stderr = nil
		if err := testCmd.Run(); err == nil {
			return true // Image exists and has configtxgen
		}
		g.log("Docker image %s exists but does not contain configtxgen", image)
		return false
	}

	// Image doesn't exist locally, but Docker is available
	// We'll try to use it anyway and let docker pull it if needed
	g.log("Docker image %s not found locally, will attempt to pull when needed", image)
	return true
}

// generateConfigtx generates the configtx.yaml file using template
func (g *Generator) generateConfigtx() (string, error) {
	return g.generateConfigtxFromTemplate()
}

// getOrdererEndpoints returns orderer endpoints for an organization
func (g *Generator) getOrdererEndpoints(org *config.OrdererOrg) []string {
	var endpoints []string
	for _, orderer := range org.Orderers {
		host := orderer.Host
		if host == "" {
			host = "localhost"
		}
		port := orderer.Port
		if port == 0 {
			port = 7050
		}

		// Format: id=<group>,broadcast,<host>:<port> for router
		// Format: id=<group>,deliver,<host>:<port> for assembler
		if orderer.Type == "router" {
			endpoints = append(endpoints, fmt.Sprintf("id=1,broadcast,%s:%d", host, port))
		} else if orderer.Type == "assembler" {
			endpoints = append(endpoints, fmt.Sprintf("id=1,deliver,%s:%d", host, port))
		}
	}
	return endpoints
}

// runConfigtxgen executes the configtxgen tool via Docker container
// Local binary support has been removed - Docker is now required
func (g *Generator) runConfigtxgen(configPath string) error {
	absOutputDir, _ := filepath.Abs(g.outputDir)
	genesisBlockPath := filepath.Join(absOutputDir, "build", "config", "configtxgen-artifacts", g.config.ChannelID+"_block.pb")

	// Always use Docker container (local binary support removed)
	return g.runConfigtxgenContainer(configPath, absOutputDir, genesisBlockPath)
}

// runConfigtxgenContainer runs configtxgen using Docker container or local binary
func (g *Generator) runConfigtxgenContainer(configPath, absOutputDir, genesisBlockPath string) error {
	if g.config.Docker.UseLocalTools {
		return g.runConfigtxgenLocal(configPath, absOutputDir, genesisBlockPath)
	}
	return g.runConfigtxgenDocker(configPath, absOutputDir, genesisBlockPath)
}

// runConfigtxgenLocal runs configtxgen using local binary
func (g *Generator) runConfigtxgenLocal(configPath, absOutputDir, genesisBlockPath string) error {
	// Check if configtxgen is available
	if _, err := exec.LookPath("configtxgen"); err != nil {
		return fmt.Errorf("configtxgen not found in PATH. Please install it or use Docker mode (set use_local_tools: false)")
	}

	// Get output directory
	outputDir := filepath.Join(absOutputDir, "build", "config", "configtxgen-artifacts")

	// Ensure output directory exists
	if err := os.MkdirAll(outputDir, 0750); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Build command
	outputBlockPath := filepath.Join(outputDir, fmt.Sprintf("%s_block.pb", g.config.ChannelID))
	configDir := filepath.Dir(configPath)

	cmd := exec.Command("configtxgen",
		"-channelID", g.config.ChannelID,
		"-profile", "OrgsChannel",
		"-configPath", configDir,
		"--outputBlock", outputBlockPath,
	)

	g.log("Running configtxgen locally: %v", cmd.Args)

	// Execute command
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("configtxgen failed: %w\nOutput: %s", err, string(output))
	}

	if g.verbose {
		fmt.Printf("Configtxgen output: %s\n", string(output))
	}

	// Log the generated genesis block location with absolute path and size
	return g.logGenesisBlock(genesisBlockPath)
}

// runConfigtxgenDocker runs configtxgen using Docker container (matching Ansible behavior)
func (g *Generator) runConfigtxgenDocker(configPath, absOutputDir, genesisBlockPath string) error {
	image := g.config.Docker.ToolsImage
	if image == "" {
		panic("No fabric-x-tool image found")
	}

	// Docker paths (matching Ansible's configtxgen_docker_output_dir)
	dockerOutputDir := "/tmp/configtxgen-artifacts"
	dockerCryptogenDir := "/tmp/cryptogen-artifacts"
	dockerArmageddonDir := "/tmp/armageddon-artifacts"

	// Get absolute paths for mounting
	outputDir := filepath.Join(absOutputDir, "build", "config", "configtxgen-artifacts")
	cryptogenArtifactsDir := filepath.Join(absOutputDir, "build", "config", "cryptogen-artifacts")
	armageddonArtifactsDir := filepath.Join(absOutputDir, "build", "config", "armageddon-artifacts")

	// Ensure directories exist
	if err := os.MkdirAll(outputDir, 0750); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Build docker run command (matching Ansible's container/start.yaml)
	args := []string{
		"run",
		"--rm", // Auto-remove container (matches container_autoremove: true)
		"-v", fmt.Sprintf("%s:%s", outputDir, dockerOutputDir),
		"-v", fmt.Sprintf("%s:%s", cryptogenArtifactsDir, dockerCryptogenDir),
		"-v", fmt.Sprintf("%s:%s", armageddonArtifactsDir, dockerArmageddonDir),
	}

	// Set user to current user (matches container_run_as_host_user: true)
	if uid := os.Getuid(); uid != 0 {
		if gid := os.Getgid(); gid != 0 {
			args = append(args, "-u", fmt.Sprintf("%d:%d", uid, gid))
		}
	}

	// Copy configtx.yaml to outputDir and replace paths with container paths
	configFile := filepath.Base(configPath)
	configInOutputDir := filepath.Join(outputDir, configFile)
	configData, err := os.ReadFile(configPath)
	if err != nil {
		return fmt.Errorf("failed to read config file: %w", err)
	}

	// Replace host paths with container paths in configtx.yaml
	configStr := string(configData)
	// Replace cryptogen artifacts path
	configStr = strings.ReplaceAll(configStr, cryptogenArtifactsDir, dockerCryptogenDir)
	// Replace armageddon artifacts path
	configStr = strings.ReplaceAll(configStr, armageddonArtifactsDir, dockerArmageddonDir)

	if err := os.WriteFile(configInOutputDir, []byte(configStr), 0644); err != nil {
		return fmt.Errorf("failed to copy config file to container directory: %w", err)
	}

	// Container command (matching Ansible's container_command)
	containerCmd := fmt.Sprintf("configtxgen -channelID %s -profile OrgsChannel -configPath %s --outputBlock %s/%s_block.pb",
		g.config.ChannelID, dockerOutputDir, dockerOutputDir, g.config.ChannelID)
	args = append(args, image, "sh", "-c", containerCmd)

	g.log("Running configtxgen via Docker: docker %v", args)

	cmd := exec.Command("docker", args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("configtxgen container failed: %w\nOutput: %s", err, string(output))
	}

	if g.verbose {
		fmt.Println(string(output))
	}

	// Log the generated genesis block location with absolute path and size
	return g.logGenesisBlock(genesisBlockPath)
}

// logGenesisBlock logs information about the generated genesis block
func (g *Generator) logGenesisBlock(genesisBlockPath string) error {
	absPath, err := filepath.Abs(genesisBlockPath)
	if err != nil {
		return fmt.Errorf("failed to get absolute path for genesis block: %w", err)
	}

	info, err := os.Stat(absPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("genesis block file was not created at expected location: %s", absPath)
		}
		return fmt.Errorf("failed to stat genesis block file: %w", err)
	}

	fmt.Printf("Genesis block generated successfully!\n")
	fmt.Printf("  Location: %s\n", absPath)
	fmt.Printf("  Size: %s\n", formatBytes(info.Size()))
	return nil
}

// log prints a message if verbose mode is enabled
func (g *Generator) log(format string, args ...interface{}) {
	if g.verbose {
		fmt.Printf("  [genesis] "+format+"\n", args...)
	}
}

// formatBytes formats bytes to human-readable format
func formatBytes(bytes int64) string {
	const unit = 1024
	if bytes < unit {
		return fmt.Sprintf("%d B", bytes)
	}
	div, exp := int64(unit), 0
	for n := bytes / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(bytes)/float64(div), "KMGTPE"[exp])
}
